# 数据库配置
database:
  host: 192.168.1.24
  port: 3307
  username: root
  password:
  database: go-test

redis:
  port: 80

# JWT 配置
jwt:
  secret: weiwei
  issuer: test
  expireSeconds: 3600

# 日志配置
log:
  level: info # debug, info, warn, error
  format: json # json, text
  output: stdout # stdout, file
  file_path: logs/app.log
  max_size: 100 # MB
  max_backups: 7
  max_age: 30 # days
  compress: true
